pipeline {
agent any
    stages {
        
        stage('Build Docker image') {
            
            steps {
                // Build the Docker image
                sh 'docker build -t test_image:1.0 .'
            }
        }
        
        stage('Docker Login') {
           
            steps {
                // Log in to the Docker registry (e.g., Docker Hub)
                sh 'docker login -u mayurgavli -p Mayur1990$'
            }
        }
        stage('Push to Docker Registry') {
            steps {
                // Push the Docker image to the registry
                sh 'docker tag test_image:1.0 mayurgavli/mayur_npn:1.6'
                sh 'docker push mayurgavli/mayur_npn:1.6'
                // Docker image pushed now
            }
        }
    }
}
